name: "[uv]: .pre-commit"

on:
  pull_request:

jobs:
  uv-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pre-commit
        run: uv run pre-commit run --all-files